
name: publish

on:
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  wheels:

    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-20.04, windows-2019, macos-11] - cannot figure out how to get libm to work on windows
        os: [ubuntu-latest, macos-latest, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.2
      env:
        CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
  publish:
    needs: [wheels]
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
      - name: Get files
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
